/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practica2.pkg3;

import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author DAM2_05
 */
public class FrameComobox extends javax.swing.JFrame {

    /**
     * Creates new form FrameComobox
     */
    private enum dam1 {
        Bases, Entornos, FOL, Lenguaje, Programación, Sistemas
    };

    private enum dam2 {
        Acceso, Interfaces, Empresas, Ingles, Procesos, Android, Gestion, Proyecto, Practicas
    }

    public FrameComobox() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Texto_Comunicativo = new javax.swing.JLabel();
        Modulo_Añadir = new javax.swing.JTextField();
        Añadir = new javax.swing.JButton();
        Modulos_Matriculados = new javax.swing.JComboBox<>();
        Borrar_Todos = new javax.swing.JButton();
        Añadir_Todos = new javax.swing.JButton();
        Cursos = new javax.swing.JComboBox<>();
        Borrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Texto_Comunicativo.setText("Añade el nombre de los módulos de los que estes matriculado");

        Modulo_Añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modulo_AñadirActionPerformed(evt);
            }
        });

        Añadir.setText("Añadir");
        Añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirActionPerformed(evt);
            }
        });

        Borrar_Todos.setText("Borrar Todos");
        Borrar_Todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Borrar_TodosActionPerformed(evt);
            }
        });

        Añadir_Todos.setText("Añadir Todos");
        Añadir_Todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Añadir_TodosActionPerformed(evt);
            }
        });

        Cursos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DAM 1", "DAM 2" }));

        Borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/trash.png"))); // NOI18N
        Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Modulo_Añadir, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Añadir)
                        .addGap(194, 194, 194)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Borrar_Todos)
                            .addComponent(Añadir_Todos)
                            .addComponent(Cursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Modulos_Matriculados, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Borrar))))
                    .addComponent(Texto_Comunicativo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(Texto_Comunicativo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Cursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Borrar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Modulo_Añadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Modulos_Matriculados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Añadir)
                    .addComponent(Añadir_Todos))
                .addGap(18, 18, 18)
                .addComponent(Borrar_Todos)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void existe(String Modulo) {
        boolean existe = true;

        for (int i = 0; i < Modulos_Matriculados.getItemCount(); i++) {
            if (Modulo.equals((String) Modulos_Matriculados.getItemAt(i))) {
                existe = false;
            }
        }
        if (existe) {
            Añadir(Modulo);
        }
    }

    public void Añadir(String Modulo) {
        Modulos_Matriculados.addItem(Modulo);
    }

    private void Modulo_AñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modulo_AñadirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Modulo_AñadirActionPerformed

    private void AñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirActionPerformed
        String Modulo = Modulo_Añadir.getText().trim();

        if (Modulo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, rellena el campo.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (Modulos_Matriculados.getItemCount() == 0) {
            Añadir(Modulo);
            return;
        }

        existe(Modulo);


    }//GEN-LAST:event_AñadirActionPerformed

    private void Borrar_TodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Borrar_TodosActionPerformed
        int cont = Modulos_Matriculados.getItemCount();
        for (int i = 0; i < cont; i++) {
            Modulos_Matriculados.removeItemAt(0);
        }
    }//GEN-LAST:event_Borrar_TodosActionPerformed

    private void Añadir_TodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Añadir_TodosActionPerformed
        String Modulo = Cursos.getSelectedItem().toString();
        System.out.println(Modulo);
        if (Modulo.equals("DAM 1")) {
            for (dam1 modulo : dam1.values()) {
                existe(modulo.toString());

            }
        }
        if (Modulo.equals("DAM 2")) {
            for (dam2 modulo : dam2.values()) {
                existe(modulo.toString());

            }
        }

    }//GEN-LAST:event_Añadir_TodosActionPerformed

    private void BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarActionPerformed

        Modulos_Matriculados.removeItem(Modulos_Matriculados.getSelectedItem());

    }//GEN-LAST:event_BorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameComobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameComobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameComobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameComobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameComobox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Añadir;
    private javax.swing.JButton Añadir_Todos;
    private javax.swing.JButton Borrar;
    private javax.swing.JButton Borrar_Todos;
    private javax.swing.JComboBox<String> Cursos;
    private javax.swing.JTextField Modulo_Añadir;
    private javax.swing.JComboBox<String> Modulos_Matriculados;
    private javax.swing.JLabel Texto_Comunicativo;
    // End of variables declaration//GEN-END:variables
}
